// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Div$default(Props) {
  var children = Props.children;
  return React.createElement("div", undefined, children);
}

var $$default = Div$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
