// Generated by ReScript, PLEASE EDIT WITH CARE

import Div from "./Div";
import * as React from "react";
import * as ResumeScss from "./Resume.scss";

var css = ResumeScss;

function s(prim) {
  return prim;
}

var make = Div;

var Txt = {
  make: make
};

function Resume$default(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement("header", {
                  className: "App-header"
                }, React.createElement("div", {
                      className: "welcomeWrapper"
                    }, React.createElement("h1", {
                          className: "welcome"
                        }, "환영합니다 !")), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "basicInfo"
                        }, React.createElement("div", {
                              className: "txt"
                            }, "기본정보")), React.createElement("div", {
                          className: "basicDescription"
                        }, React.createElement("pre", undefined, React.createElement("span", {
                                  className: "highlight"
                                }, "웹 프론트엔드"), " 개발자 입니다"))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "titleWrapper center"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "간단이력")), React.createElement("h3", undefined)), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, "NE능률", React.createElement("div", {
                                      className: "sub"
                                    }, "- 2022.02 ~ 현재"), React.createElement("div", {
                                      className: "sub"
                                    }, "- 학생 커뮤니티 앱 공작소를 개발중입니다")), React.createElement("li", undefined, "개인사업", React.createElement("div", {
                                      className: "sub"
                                    }, "- 2019.01 ~ 현재"), React.createElement("div", {
                                      className: "sub"
                                    }, "- 개인사업 하면서 남는 시간에 리액트 위주로 웹개발을 독학하였습니다")), React.createElement("li", undefined, "해바라기소프트", React.createElement("div", {
                                      className: "sub"
                                    }, "- 2018.05 ~ 2018.11"), React.createElement("div", {
                                      className: "sub"
                                    }, "- 웹개발입문. 스프링 + 제이쿼리로 사이트 구현")), React.createElement("li", undefined, "파워보이스", React.createElement("div", {
                                      className: "sub"
                                    }, "- 2017.01 ~ 2017.12"), React.createElement("div", {
                                      className: "sub"
                                    }, "- C++ & 파이썬으로 자연어처리(NLP) 업무 수행")), React.createElement("li", undefined, "건국대 컴공", React.createElement("div", {
                                      className: "sub"
                                    }, "- 2015.03 ~ 2017.02"), React.createElement("div", {
                                      className: "sub"
                                    }, "- 편입하여 3~4학년 과정을 이수하였습니다"))))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "titleWrapper center"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "핵심역량")), React.createElement("h3", undefined), React.createElement("div", {
                              className: "imgWrapper core"
                            }, React.createElement("img", {
                                  className: "img_tech",
                                  src: "js-logo.png"
                                }), React.createElement("img", {
                                  className: "img_tech",
                                  src: "ts-logo.png"
                                }), React.createElement("img", {
                                  className: "img_tech",
                                  src: "express-logo-2.png"
                                }), React.createElement("img", {
                                  className: "img_tech",
                                  src: "react-logo.png"
                                }), React.createElement("img", {
                                  className: "img_tech",
                                  src: "nextjs-logo.svg"
                                }), React.createElement("img", {
                                  className: "img_tech",
                                  src: "tailwind-logo-2.png"
                                }), React.createElement("img", {
                                  className: "img_tech",
                                  src: "cypress-logo.png"
                                }))), React.createElement("div", {
                          className: "description"
                        }, React.createElement("li", undefined, React.createElement("strong", undefined, "react, next.js"), " 기반의 웹개발을 수행합니다"), React.createElement("li", undefined, "프로젝트 생성에서 배포까지 개발 전과정 진행이 가능합니다"), React.createElement("li", undefined, React.createElement("strong", undefined, "Relay"), "등의 GraphQL 라이브러리를 사용합니다"), React.createElement("li", undefined, "SoC원칙에 입각하여 리액트 컴포넌트를 개발합니다"), React.createElement("li", undefined, "ES2022까지 ", React.createElement("strong", undefined, "ECMA 스펙"), "에 대한 거의 모든것을 이해합니다 (promise, generator, async 등)"), React.createElement("li", undefined, "jQuery 없이 querySelector등의 ", React.createElement("strong", undefined, "웹표준 API만으로 엘리먼트를 조작"), "하는데 불편함이 없습니다"), React.createElement("li", undefined, "크로미움의 렌더링 프로세스에 입각하여 성능저하가 없도록 신경씁니다"), React.createElement("li", undefined, "js 런타임 환경에 입각하여 ", React.createElement("strong", undefined, "코드의 실행순서를 제대로 이해"), "합니다"), React.createElement("li", undefined, "퍼포먼스 최적화를 선호합니다 (CLS, TTI, LCP등)"), React.createElement("li", undefined, React.createElement("strong", undefined, "SCSS, CSS Module, tailwind"), " 기반의 스타일링을 지향합니다"), React.createElement("li", undefined, React.createElement("strong", undefined, "반응형 웹 디자인"), "을 수행하였습니다"), React.createElement("li", undefined, "영어 리딩 리스닝 가능하며 ", React.createElement("strong", undefined, "공식문서 리딩"), "을 지향합니다"), React.createElement("li", undefined, "E2E 테스트를 수행합니다"), React.createElement("li", undefined, "네트워크 IO시에 예외처리 및 런타임 타입체킹에 신경씁니다"))), React.createElement("div", {
                      className: "strong_font white"
                    }, React.createElement("h1", undefined, "경력")), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "titleWrapper"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "NE 능률")), React.createElement("h4", undefined, React.createElement("i", undefined, "(2022.02 ~)")), React.createElement("h3", undefined, React.createElement("i", undefined, "프리랜서로 학생 커뮤니티 앱 공작소의 고도화 작업을 수행하였습니다")), React.createElement("div", {
                              className: "imgWrapper ne"
                            }, React.createElement("img", {
                                  className: "general-logo",
                                  src: "ts-logo.png"
                                }), React.createElement("img", {
                                  className: "general-logo",
                                  src: "react-logo.png"
                                }), React.createElement("img", {
                                  className: "general-logo",
                                  src: "cypress-logo.png"
                                }), React.createElement("img", {
                                  className: "general-logo",
                                  src: "tailwind-logo-2.png"
                                }))), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, "페이지 단위로 레이지 로딩을 적용하여 랜딩페이지 로딩을 약 300ms 감소시켰습니다"), React.createElement("li", undefined, "레이지로딩 및 웹팩 번들링 최적화로 랜딩페이지의 js사이즈를 837kB -> 191kB로 약 77.2% 감소시켰습니다")))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "titleWrapper"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "개발자 커뮤니티 사이트 구현")), React.createElement("h4", undefined, React.createElement("i", undefined, "(2021.01 ~ )")), React.createElement("h3", undefined, React.createElement("i", undefined, "(1인 프로젝트)")), React.createElement("h3", undefined, React.createElement("i", undefined, "개발 커뮤니티에서 읽을만한 글을 한데모아 게시판 형태로 보여주는 웹사이트입니다")), React.createElement("img", {
                              className: "next-title-logo",
                              src: "nextjs-logo.svg",
                              width: "240px"
                            })), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, "참여도 : 100%"), React.createElement("li", undefined, "URL : https://devkr.info"), React.createElement("li", undefined, "타입스크립트와 SCSS 기반으로 구현하였습니다"), React.createElement("li", undefined, "헤드리스 크롬 라이브러리인 puppeteer로 reddit, okky, dcinside의 글을 스크래핑하여 DB에 저장하였습니다"), React.createElement("li", undefined, "회원가입 및 로그인 페이지를 구현했습니다"), React.createElement("li", undefined, "MongoDB Realm 및 GraphQL기반의 데이터 요청으로 게시판을 구현했습니다"), React.createElement("li", undefined, "게시물 검색기능을 구현했습니다"), React.createElement("li", undefined, "자유게시판의 글등록, 삭제, 댓글쓰기 및 스크롤에 반응하는 글 로딩하기 기능을 구현했습니다"), React.createElement("li", undefined, "모바일 및 데스크탑 페이지를 별도로 만들지 않고 디바이스에 맞춰 동적으로 변하는 반응형 웹으로 구현했습니다"), React.createElement("li", undefined, "서버리스 기반의 AWS Lambda@Edge, Cloudfront를 이용하여 배포했습니다"), React.createElement("li", undefined, "스택", React.createElement("ul", undefined, React.createElement("li", undefined, "Next.js, recoil, CSS Module, SCSS, styled-jsx"), React.createElement("li", undefined, "DB : MongoDB Atlas, Mongodb Realm(GraphQL 기반)"), React.createElement("li", undefined, "배포툴 : serverless프레임워크의 next-js 플러그인 (aws cloudfront로 디플로이)"), React.createElement("li", undefined, "스크랩핑 툴 : puppeteer")))))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "titleWrapper"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "학생 출결관리 사이트 구현")), React.createElement("h4", undefined, React.createElement("i", undefined, "(2020.01 ~)")), React.createElement("h3", undefined, React.createElement("i", undefined, "(1인 프로젝트)")), React.createElement("img", {
                              className: "next-title-logo",
                              src: "nextjs-logo.svg",
                              width: "240px"
                            })), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, "참여도 : 100%"), React.createElement("li", undefined, "next.js기반으로 제작되었습니다"), React.createElement("li", undefined, "next-iron-session에 기반한 로그인 기능을 구현했습니다"), React.createElement("li", undefined, "학생이 과목을 신청하거나 신청을 취소하는 페이지를 만들었습니다"), React.createElement("li", undefined, "선생님이 과목에 등록한 학생 정보를 열람하는 페이지를 만들었습니다"), React.createElement("li", undefined, "mongoDB atlas를 DB로 사용했습니다"), React.createElement("li", undefined, "API Routes에 기반한 DB CRUD를 구현했습니다"), React.createElement("li", undefined, "함수형 컴포넌트 및 훅에 기반하여 페이지를 구현했습니다"), React.createElement("li", undefined, "AWS EC2로 배포했습니다")))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "titleWrapper"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "커뮤니티 베스트글 모음 사이트 구현")), React.createElement("h4", undefined, React.createElement("i", undefined, "(2019.01 ~ 2019.10)")), React.createElement("h3", undefined, React.createElement("i", undefined, "(1인 프로젝트)")), React.createElement("img", {
                              className: "express-title-logo",
                              src: "express-logo-2.png",
                              width: "350px"
                            })), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, "참여도 : 100%"), React.createElement("li", undefined, "express & pug 템플릿 엔진 기반으로 제작된 사이트입니다"), React.createElement("li", undefined, "PhantomJS로 각종 커뮤니티의 베스트 글을 크롤링하여 DB에 저장하였습니다"), React.createElement("li", undefined, "heroku의 MongoDB 애드온즈를 DB로 사용하여 스크랩한 데이터를 관리했습니다"), React.createElement("li", undefined, "REST기반의 API를 작성했습니다"), React.createElement("li", undefined, "페이지네이션 및 검색 기능이 포함된 게시판을 구현했습니다"), React.createElement("li", undefined, "SEO(Search Engine Optimization)를 적용하여 페이지뷰를 증가시킨 경험이 있습니다"), React.createElement("li", undefined, "heroku로 배포하였습니다")))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "titleWrapper center"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "해바라기 소프트")), React.createElement("h4", undefined, React.createElement("i", undefined, "(2018.05 ~ 2018.10)")), React.createElement("h4", undefined, React.createElement("i", undefined, "전자투표 솔루션 업체에서 프론트 및 백엔드 엔지니어로 업무를 수행 하였습니다")), React.createElement("img", {
                              src: "spring_logo.png",
                              width: "200px"
                            }), React.createElement("img", {
                              src: "thymeleaf_logo.png",
                              width: "180px"
                            }), React.createElement("img", {
                              src: "jquery_logo.png",
                              width: "250px"
                            })), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, "스프링 + 타임리프 + 제이쿼리 기반의 프로젝트를 수행하였습니다"), React.createElement("li", undefined, "투표결과를 엑셀파일로 생성하는 기능을 구현하였습니다", React.createElement("div", {
                                      className: "sub"
                                    }, "- 사내 자체제작된 ORM으로 MySQL에서 투표관련 데이터를 가져와서 엑셀 파일로 제작하여 클라이언트에게 리스폰스 해주는 기능을 구현하였습니다")), React.createElement("li", undefined, "chart.js라는 js기반의 데이터 시각화 라이브러리로 투표 결과를 시각화하는 페이지를 10여개 제작하였습니다", React.createElement("div", {
                                      className: "sub"
                                    }, "- 막대 그래프, 원형 그래프 등의 다양한 그래프로 투표 결과를 시각화하였습니다")), React.createElement("li", undefined, "타임리프 & 제이쿼리 기반으로 게시판을 구현하였습니다", React.createElement("div", {
                                      className: "sub"
                                    }, "- \"글 작성하기, 글 수정하기, 글 상세보기\" 등의 페이지를 제작하였습니다"))))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "titleWrapper center"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "파워보이스")), React.createElement("h4", undefined, React.createElement("i", undefined, "(2017.01 ~ 2017.12)")), React.createElement("h4", undefined, React.createElement("i", undefined, "자연어처리 업무를 담당하였습니다")), React.createElement("img", {
                              className: "powervoiceImg",
                              src: "cpp-logo.png",
                              width: "200px"
                            }), React.createElement("img", {
                              className: "powervoiceImg",
                              src: "python-logo2.png",
                              width: "200px"
                            })), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, "구어체 문장의 패턴을 분석하여 특정 명령어로 분류하는 classification 작업을 수행하였습니다"), React.createElement("li", undefined, "형태소 분석기 엔진을 최적화하여 타겟 키워드의 검출을 약 5% 향상시켰습니다"), React.createElement("li", undefined, "형태소 분석기 전체 리팩토링 작업을 수행했습니다", React.createElement("ul", {
                                      className: "sub_ul"
                                    }, React.createElement("li", undefined, React.createElement("i", undefined, "C기반의 전체 소스코드를 C++로 리팩토링 하였습니다.")), React.createElement("li", undefined, React.createElement("i", undefined, "전체적인 코드가 비효율적으로 작성되었다고 판단되었기 때문입니다")), React.createElement("li", undefined, React.createElement("i", undefined, "중복되는 코드를 제거하고 코드 재사용성을 높이고 문법을 간결하게 작성하여 코드길이를 약 1/5로 줄였습니다")), React.createElement("li", undefined, React.createElement("i", undefined, "문자열 검색 알고리즘을 boyer-moore에서 aho-corasick으로 대체하고 파일 I/O횟수를 최소화하여 이전엔진 대비 처리속도를 약 2.8배 향상시켰습니다")), React.createElement("li", undefined, React.createElement("i", undefined, "사용하는 메모리 사이즈를 약 50% 줄였습니다")))), React.createElement("li", undefined, "문자열에서 키워드를 검출하는 수작업을 프로그램으로 자동화 하였습니다", React.createElement("ul", {
                                      className: "sub_ul"
                                    }, React.createElement("li", undefined, React.createElement("i", undefined, "\"여기 불났어요\"같은 문장에서 \"불나다\" 라는 어휘를 검출하는 작업을 파이썬으로 100% 자동화 하였습니다")), React.createElement("li", undefined, React.createElement("i", undefined, "약 6개월 걸릴것으로 예상했던 작업이 3주만에 완료 되었습니다.")), React.createElement("li", undefined, React.createElement("i", undefined, "직원들이 다른 업무에 집중할 수 있게되어 팀 전체의 생산성이 증대 되었습니다"))))))), React.createElement("div", {
                      className: "strong_font white"
                    }, React.createElement("h1", undefined, React.createElement("b", undefined, "기술"))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "titleWrapper"
                        }, React.createElement("img", {
                              className: "img_title js_title_logo",
                              src: "js_icon.png",
                              width: "200px"
                            }), React.createElement("p", {
                              className: "mobile_title"
                            }, React.createElement("strong", undefined, "Javascript"))), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, "ES1부터 ES2022까지 ", React.createElement("strong", undefined, "거의 모든 문법"), "을 읽고 쓰고 이해할 수 있습니다"), React.createElement("li", undefined, "콜백과 이벤트 루프, 프라미스와 마이크로테스크 큐, async함수 및 자바스크립트 런타임에서 ", React.createElement("strong", undefined, "코드가 어떤 순서대로 실행"), "되는지, 왜 그렇게 실행되는지 이해할 수 있습니다."), React.createElement("li", undefined, "코드의 실행흐름이 이해가지 않아서 버그가 발생하는 일이 없습니다"), React.createElement("li", undefined, "jQuery 없이 querySelector및 HTMLElement등의 Web API로 ", React.createElement("strong", undefined, "엘리먼트를 다루고 조작"), "하는데 불편함이 없습니다"), React.createElement("li", undefined, "필요한 ", React.createElement("strong", undefined, "정규식"), "은 대부분 이해하고 구현할 수 있습니다"), React.createElement("li", undefined, "함수형의 원칙인 순수함수의 지향 및 ", React.createElement("strong", undefined, "부수효과의 최소화"), "에 입각하여 개발합니다"), React.createElement("li", undefined, "읽기쉬운 코드가 최고의 코드라는 가치에 입각하여 누가 언제 읽어도 이해할 수 있도록 ", React.createElement("strong", undefined, "선언적"), "으로 개발합니다")))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "titleImgWrapper"
                        }, React.createElement("img", {
                              className: "img_title ts_title_logo",
                              src: "ts_logo.svg"
                            })), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, "any 및 강제 형변환을 지양하고 타입가드를 통한 타입 추론을 지향합니다")))), React.createElement("div", {
                      className: "project react_wrapper"
                    }, React.createElement("div", {
                          className: "titleReactImgWrapper"
                        }, React.createElement("img", {
                              className: "img_title react_title_img",
                              src: "react_icon_square.png"
                            })), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("strong", undefined, "React hooks"), "기반의 함수형 컴포넌트 기반으로 개발합니다"), React.createElement("li", undefined, React.createElement("strong", undefined, "SoC"), "철학에 기반하여 컴포넌트를 분리하여 작성합니다"), React.createElement("li", undefined, "React Fiber기반의 리컨사일러가 어떤 타이밍에 컴포넌트를 재호출하고 언제 이펙트함수 등이 호출되는지 ", React.createElement("strong", undefined, "실행흐름"), "을 이해할 수 있습니다"), React.createElement("li", undefined, "함수형 컴포넌트 기반에 필수적인 ", React.createElement("strong", undefined, "클로저"), "의 작동원리를 숙지하고 있습니다")))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "titleWrapper center"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "기타 언어")), React.createElement("div", {
                              className: "imgWrapper toyProject"
                            }, React.createElement("img", {
                                  className: "rescript_title_logo",
                                  src: "rescript-logo.svg"
                                }), React.createElement("img", {
                                  className: "elm-logo",
                                  src: "elm_logo.png"
                                }), React.createElement("img", {
                                  className: "cljs-logo",
                                  src: "cljs-logo.png"
                                }))), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, "몇가지 토이프로젝트를 수행하였습니다")))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "titleWrapper center"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "배포")), React.createElement("img", {
                              className: "deploy_icon",
                              src: "deploy_icon.png"
                            }), React.createElement("h3", undefined)), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, "서버 플랫폼인 AWS EC2, Heroku로 배포한 경험이 있습니다"), React.createElement("li", undefined, "잼스택 플랫폼인 AWS Cloudfront, Cloudflare Pages로 배포한 경험이 있습니다"), React.createElement("li", undefined, "정적 사이트 플랫폼인 Netlify, Github Pages, NCP ObjectStorage로 배포한 경험이 있습니다")))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "private"
                        }, React.createElement("div", undefined, React.createElement("h1", undefined, React.createElement("b", undefined, "개인정보")), React.createElement("h3", undefined, React.createElement("i", undefined)), React.createElement("img", {
                                  className: "personal_info_icon",
                                  src: "/profile_icon.png",
                                  width: "150px"
                                }))), React.createElement("div", {
                          className: "descriptionWrapper"
                        }, React.createElement("div", {
                              className: "descriptItem"
                            }, React.createElement("div", {
                                  className: "upper"
                                }, "기술블로그"), React.createElement("div", {
                                  className: "lower"
                                }, React.createElement("a", {
                                      href: "https://blog.devkr.info"
                                    }, "blog.devkr.info"))), React.createElement("div", {
                              className: "descriptItem"
                            }, React.createElement("div", {
                                  className: "upper"
                                }, React.createElement("img", {
                                      className: "icon",
                                      src: "https://cdn-icons-png.flaticon.com/512/25/25231.png"
                                    }), "Github"), React.createElement("div", {
                                  className: "lower"
                                }, React.createElement("a", {
                                      href: "https://github.com/coleea?tab=repositories"
                                    }, "github.com/coleea"), React.createElement("div", {
                                      className: "sub"
                                    }, "- 주로 공부한 내용을 올려둡니다"))), React.createElement("div", {
                              className: "descriptItem"
                            }, React.createElement("div", {
                                  className: "upper"
                                }, React.createElement("img", {
                                      className: "icon",
                                      height: "30px",
                                      src: "https://cdn-icons-png.flaticon.com/512/174/174857.png"
                                    }), "링크드인"), React.createElement("div", {
                                  className: "lower"
                                }, React.createElement("a", {
                                      href: "https://www.linkedin.com/in/leekb86/"
                                    }, "linkedin.com/in/leekb86"))), React.createElement("div", {
                              className: "descriptItem"
                            }, React.createElement("div", {
                                  className: "upper"
                                }, "Phone"), React.createElement("div", {
                                  className: "lower"
                                }, "010-9333-3385")), React.createElement("div", {
                              className: "descriptItem"
                            }, React.createElement("div", {
                                  className: "upper"
                                }, "이름"), React.createElement("div", {
                                  className: "lower"
                                }, "이국범")))), React.createElement("footer", undefined, "본 이력서는 ", React.createElement("img", {
                          className: "rescript_logo",
                          alt: "rescript",
                          src: "rescript-logo.svg",
                          width: "150px"
                        }), " , ", React.createElement("img", {
                          className: "astro_logo",
                          alt: "astro.build",
                          src: "astro_logo.jpg",
                          width: "50px"
                        }), " 로 작성되었고 Cloudflare Pages에 배포되었습니다")));
}

var $$default = Resume$default;

export {
  css ,
  s ,
  Txt ,
  $$default ,
  $$default as default,
  
}
/* css Not a pure module */
