// Generated by ReScript, PLEASE EDIT WITH CARE

import Div from "./Div";
import * as React from "react";
import * as ResumeScss from "./Resume.scss";

var css = ResumeScss;

var make = Div;

var Txt = {
  make: make
};

function Resume$default(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement("header", {
                  className: "App-header"
                }, React.createElement("img", {
                      className: "welcome_img",
                      src: "/welcome.png"
                    }), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "title center"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "기본정보"))), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("div", {
                                      className: "highlight"
                                    }, "웹 프론트엔드 "), " 개발자 입니다")))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "title center"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "간단이력")), React.createElement("h3", undefined)), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, "건국대 컴공", React.createElement("div", {
                                      className: "sub"
                                    }, "- 2015.03 ~ 2017.02"), React.createElement("div", {
                                      className: "sub"
                                    }, "- 편입하여 3~4학년 과정을 이수하였습니다")), React.createElement("li", undefined, "파워보이스", React.createElement("div", {
                                      className: "sub"
                                    }, "- 2017.01 ~ 2017.12"), React.createElement("div", {
                                      className: "sub"
                                    }, "- C++ & 파이썬으로 자연어처리(NLP) 업무 수행")), React.createElement("li", undefined, "해바라기소프트", React.createElement("div", {
                                      className: "sub"
                                    }, "- 2018.05 ~ 2018.11"), React.createElement("div", {
                                      className: "sub"
                                    }, "- 웹개발입문. 스프링 + 제이쿼리로 사이트 구현")), React.createElement("li", undefined, "개인사업", React.createElement("div", {
                                      className: "sub"
                                    }, "- 2019.01 ~ 현재"), React.createElement("div", {
                                      className: "sub"
                                    }, "- 개인사업 하면서 남는 시간에 리액트 위주로 웹개발을 독학하였습니다"))))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "title center"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "핵심역량")), React.createElement("h3", undefined), React.createElement("img", {
                              className: "img_tech",
                              src: "https://sc372.github.io/2017/05/30/javascript-intro/javascript.png"
                            }), React.createElement("img", {
                              className: "img_tech",
                              src: "https://i.pinimg.com/736x/c3/8e/e8/c38ee8475ee7f3680f706c56c3a1194c.jpg"
                            }), React.createElement("img", {
                              className: "img_tech",
                              src: "https://upload.wikimedia.org/wikipedia/commons/6/64/Expressjs.png"
                            }), React.createElement("img", {
                              className: "img_tech",
                              src: "https://logos-download.com/wp-content/uploads/2016/09/React_logo_wordmark.png"
                            }), React.createElement("img", {
                              className: "img_tech",
                              src: "https://res.cloudinary.com/practicaldev/image/fetch/s--kpVkTsRw--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/r7kj8y4dfyd1aw989edi.png"
                            }), React.createElement("img", {
                              className: "img_tech",
                              src: "https://poiemaweb.com/img/mongo-db-logo.png"
                            })), React.createElement("div", undefined, React.createElement("li", undefined, React.createElement("strong", undefined, "next.js"), " 또는 ", React.createElement("strong", undefined, "express"), " 기반의 웹개발을 수행합니다"), React.createElement("li", undefined, "프로젝트 생성에서 배포 및 도메인 연결까지 개발 전과정을 혼자 진행할 수 있습니다"), React.createElement("li", undefined, "Next.js의 ", React.createElement("strong", undefined, "API Routes"), "를 통하여 ", React.createElement("strong", undefined, "MongoDB"), "의 CRUD가 가능합니다"), React.createElement("li", undefined, React.createElement("strong", undefined, "MongoDB Atlas"), "및 ", React.createElement("strong", undefined, "Supabase"), "기반의 DB 생성 및 관리가 가능합니다"), React.createElement("li", undefined, "함수형 컴포넌트를 이용하여 SoC원칙에 입각하여 리액트 컴포넌트를 개발합니다"), React.createElement("li", undefined, "ES2021까지 ", React.createElement("strong", undefined, "ECMA 스펙"), "에 대한 거의 모든것을 이해합니다 (promise, generator, async 등)"), React.createElement("li", undefined, "jQuery 없이 querySelector및 HTMLElement등의 ", React.createElement("strong", undefined, "웹표준 API만으로 엘리먼트를"), " 조작하는데 불편함이 없습니다"), React.createElement("li", undefined, "웹브라우저의 렌더링 프로세스 및 js 런타임 환경에 입각하여 ", React.createElement("strong", undefined, "코드의 실행순서를 이해"), "할 수 있습니다"), React.createElement("li", undefined, React.createElement("strong", undefined, "SCSS, CSS Module"), " 기반의 스타일링을 지향합니다"), React.createElement("li", undefined, "디바이스에 따라서 가변적으로 표현되는 ", React.createElement("strong", undefined, "반응형 웹 디자인"), " 경험이 존재합니다"), React.createElement("li", undefined, "영문독해, 쓰기, 리스닝 가능하며 ", React.createElement("strong", undefined, "공식문서 리딩"), "을 지향합니다. 인터넷 검색만으로 해결이 불가능한 문제 발생시 스택오버플로우 및 개발 커뮤니티에 영문으로 커뮤니케이션하여 문제해결한 건이 다수 존재합니다"), React.createElement("li", undefined, React.createElement("strong", undefined, "flutter"), "기반의 모바일 앱을 개발하여 플레이스토어에 출시한 경력이 존재합니다"))), React.createElement("div", {
                      className: "strong_font"
                    }, React.createElement("h1", undefined, "경력")), React.createElement("div", {
                      className: "strong_font"
                    }, React.createElement("h1", undefined, React.createElement("b", undefined, "기술"))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "title"
                        }, React.createElement("img", {
                              className: "img_title",
                              src: "https://i.pinimg.com/736x/c3/8e/e8/c38ee8475ee7f3680f706c56c3a1194c.jpg"
                            }), React.createElement("p", {
                              className: "mobile_title"
                            }, React.createElement("strong", undefined, "Typescript"))), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, "any 및 강제 형변환을 지양하고 타입가드를 통한 타입 추론을 지향합니다")))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "title"
                        }, React.createElement("img", {
                              className: "img_title",
                              src: "https://logos-download.com/wp-content/uploads/2016/09/React_logo_wordmark.png"
                            }), React.createElement("p", {
                              className: "mobile_title"
                            }, React.createElement("strong", undefined, "React"))), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("strong", undefined, "React hooks"), "기반의 함수형 컴포넌트 기반으로 개발합니다"), React.createElement("li", undefined, React.createElement("strong", undefined, "SoC"), "철학에 기반하여 컴포넌트를 분리하여 작성합니다"), React.createElement("li", undefined, "React Fiber기반의 리컨사일러가 어떤 타이밍에 컴포넌트를 재호출하고 언제 이펙트함수 등이 호출되는지 ", React.createElement("strong", undefined, "실행흐름"), "을 이해할 수 있습니다"), React.createElement("li", undefined, "함수형 컴포넌트 기반에 필수적인 ", React.createElement("strong", undefined, "클로저"), "의 작동원리를 숙지하고 있습니다")))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "title center"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "배포")), React.createElement("img", {
                              className: "deploy_icon",
                              src: "https://media.istockphoto.com/vectors/space-rocket-ship-launch-icon-symbol-sign-vector-illustration-icon-vector-id1249577261?k=20&amp;m=1249577261&amp;s=170667a&amp;w=0&amp;h=XWXNf2eItfPfuRe67N5-6dqcPRH745bvbDInj74Xv3w="
                            }), React.createElement("h3", undefined)), React.createElement("div", {
                          className: "description"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, "서버 플랫폼인 AWS EC2, Heroku로 배포한 경험이 있습니다"), React.createElement("li", undefined, "잼스택 플랫폼인 AWS Cloudfront, Cloudflare Pages로 배포한 경험이 있습니다"), React.createElement("li", undefined, "정적 사이트 플랫폼인 Netlify, Github Pages, NCP ObjectStorage로 배포한 경험이 있습니다")))), React.createElement("div", {
                      className: "project"
                    }, React.createElement("div", {
                          className: "title center"
                        }, React.createElement("h1", undefined, React.createElement("b", undefined, "개인정보")), React.createElement("h3", undefined, React.createElement("i", undefined)), React.createElement("img", {
                              className: "personal_info_icon",
                              src: "https://www.pinclipart.com/picdir/big/247-2473891_personal-information-svg-png-icon-free-download-clipart.png",
                              width: "150px"
                            })), React.createElement("div", {
                          className: "descriptionWrapper"
                        }, React.createElement("div", {
                              className: "descriptItem"
                            }, React.createElement("div", {
                                  className: "upper"
                                }, "기술블로그"), React.createElement("div", {
                                  className: "lower"
                                }, React.createElement("a", {
                                      href: "https://blog.devkr.info"
                                    }, "blog.devkr.info"))), React.createElement("div", {
                              className: "descriptItem"
                            }, React.createElement("div", {
                                  className: "upper"
                                }, React.createElement("img", {
                                      className: "icon",
                                      src: "https://cdn-icons-png.flaticon.com/512/25/25231.png"
                                    }), "Github"), React.createElement("div", {
                                  className: "lower"
                                }, React.createElement("a", {
                                      href: "https://github.com/coleea?tab=repositories"
                                    }, "github.com/coleea"), React.createElement("div", {
                                      className: "sub"
                                    }, "- 주로 공부한 내용을 올려둡니다"))), React.createElement("div", {
                              className: "descriptItem"
                            }, React.createElement("div", {
                                  className: "upper"
                                }, React.createElement("img", {
                                      className: "icon",
                                      height: "30px",
                                      src: "https://cdn-icons-png.flaticon.com/512/174/174857.png"
                                    }), "링크드인"), React.createElement("div", {
                                  className: "lower"
                                }, React.createElement("a", {
                                      href: "https://www.linkedin.com/in/leekb86/"
                                    }, "linkedin.com/in/leekb86"))), React.createElement("div", {
                              className: "descriptItem"
                            }, React.createElement("div", {
                                  className: "upper"
                                }, "Phone"), React.createElement("div", {
                                  className: "lower"
                                }, "010-9333-3385")), React.createElement("div", {
                              className: "descriptItem"
                            }, React.createElement("div", {
                                  className: "upper"
                                }, "이름"), React.createElement("div", {
                                  className: "lower"
                                }, "이국범")))), React.createElement("footer", undefined, "Powered by Rescript, Astro, Cloudflare Pages")));
}

var $$default = Resume$default;

export {
  css ,
  Txt ,
  $$default ,
  $$default as default,
  
}
/* css Not a pure module */
