// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TestModuleScss from "./test.module.scss";

var css = TestModuleScss;

function Test$default(Props) {
  return React.createElement("div", undefined, React.createElement("div", {
                  className: css.test
                }, "테스jjjk트111. yes"));
}

var $$default = Test$default;

export {
  css ,
  $$default ,
  $$default as default,
  
}
/* css Not a pure module */
